### ISSUE TITLE
Use UTF-8 and column names without special characters

### ISSUE THREAD

**Issue by LDalby** [Aarhus-University-MPE/BioDiscover#63] opened 2023-05-03 11:10 UTC
### Description of the new feature / enhancement

Current headers have µ, (, empty spaces etc. 

I suggest that the columns get names with no special characters and get UTF-8 encoding.

### Scenario when this would be used?

Important in most programming languages I use.

**Comment by MadsR** [comment] 2023-05-06 17:33
Duplicate of #27

**Closed by MadsR** 2023-05-06 17:33 UTC
Labels: enhancement
